### ISSUE TITLE
AuxPoW chain support

### ISSUE THREAD

**Issue by JeremyRand** [in3rsha/bitcoin-mining-distribution#4]
The blockchain parsing code used here is unlikely to work out of the box with merge-mined sidechains (e.g. Namecoin) due to the different header structure.  I've rewritten the relevant code to work with sidechains (it pulls the coinbase string/address from the parent chain, since that seems to be most reliable in practice).  Would you accept a PR for this support?  (It's basically just an `auxpow-iterate.py` file that the user can run instead of `bitcoin-iterate.sh`; shouldn't be invasive.)

**Comment by in3rsha** [comment]
Sure. If it works I don't see why not.
